[build]
  functions = "netlify/functions"
  publish = "dist"

[functions]
  python_runtime = "python3.8"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/app/login"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/app/dashboard"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200