services:
  - type: web
    name: my-plant-nursery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run_web:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: run_web.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-plant-nursery-db
          property: connectionString
